---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: Course Setup
- type: document
  path: pages/lesson-index.md
  label: Lessons Index
- type: heading
  label: Structure
- type: directory
  path: _lessons
  label: Lessons
  create: all
  match: "**/*"
  templates:
  - lesson_builder
- type: heading
  label: Course Content
- type: directory
  path: _lectures
  label: Lectures
  create: all
  match: "**/*"
  templates:
  - lesson-lecture
- type: directory
  path: _readings
  label: Readings
  create: all
  match: "**/*"
  templates:
  - lesson-reading
- type: directory
  path: _assignments
  label: Assignments
  create: all
  match: "**/*"
  templates:
  - assignment-builder
- type: directory
  path: _quizzes
  label: Quizzes
  create: all
  match: "**/*"
  templates:
  - self-check-quiz
- type: jekyll-pages
  label: Pages
  create: all
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    -d _site
