---
label: learning-modules-config
hide_body: true
fields:
- name: layout
  type: text
  config:
    required: false
  label: Layout
  default: lesson-index
  hidden: true
- type: text
  name: title
  label: title
- type: boolean
  name: breadcrumb
  label: breadcrumb
- type: boolean
  name: header_image
  label: header
- type: text
  name: permalink
  label: permalink
- name: enable_lessons_by_week
  type: boolean
  label: Enable Lessons By Week
  default: true
- name: weeks
  type: field_group_list
  fields:
  - name: week_number
    type: text
    config:
      required: false
      min: 1
      max: 2
    label: Week Number
    default: '1'
    description: The week the lesson should be displayed. Typically between 1 and
      15 depending on the length of the semester.
  - name: enabled
    type: boolean
    label: enabled
  - name: publish_delay
    type: boolean
    label: Publish Delay
  - name: visible
    type: datetime
    label: visible
    description: Enter the date this week should appear
    config:
      required: false
      date_format: 
      time_format: ''
      display_utc: false
      export_format: YYYY-MM-DDTh:mm:A
    showOnly:
      field: publish_delay
      value: true
  - name: start_date
    type: datetime
    label: start date
    description: ''
    config:
      required: false
      date_format: 
      time_format: ''
      display_utc: false
      export_format: YYYY-MM-DDTh:mm:A
  - name: end_date
    type: datetime
    description: ''
    config:
      required: false
      date_format: 
      time_format: ''
      display_utc: false
      export_format: YYYY-MM-DDTh:mm:A
    label: end date
  - name: lessons
    type: list
    config:
      use_select: true
      min: 
      max: 
      source:
        type: pages
        section: lessons
    label: Lessons
    description: Choose lessons for the week.
  config:
    min: 
    max: 
    labelField: week_number
  showOnly:
    field: enable_lessons_by_week
    value: true
  label: Week
pages:
- index.md
- pages/lesson-index.md
