---
label: learning-modules-config
hide_body: true
fields:
- name: layout
  type: text
  config:
    required: false
  label: Layout
  default: lesson-index
  hidden: true
- type: text
  name: title
  label: title
- type: boolean
  name: breadcrumb
  label: breadcrumb
- type: boolean
  name: header
  label: header
- type: text
  name: permalink
  label: permalink
- name: enable_lessons_by_week
  type: boolean
  label: Enable Lessons By Week
  default: true
pages:
- pages/lesson-index.md
