name: Build and Deploy

on:
  push:
    branches: [master]
  schedule:
    # * is a special character in YAML so you have to quote this string
    #- cron:  '59 23 * * *' # 11:59pm UTC (~3am)
    - cron:  '4 25 * * *' # 11:59pm UTC (~3am)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Install dependencies
        run: bundle install
      - name: Build Jekyll
        run: bundle exec jekyll build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: _site # The folder the action should deploy.
